export const timezones = [
  "ACDT - Australian Central Daylight Time (UTC+10:30)",
  "ACST - Australian Central Standard Time (UTC+9:30)",
  "ACT - ASEAN Common Time (UTC+8)",
  "ADT - Atlantic Daylight Time (UTC-3)",
  "AEDT - Australian Eastern Daylight Time (UTC+11)",
  "AEST - Australian Eastern Standard Time (UTC+10)",
  "AFT - Afghanistan Time (UTC+4:30)",
  "AKDT - Alaska Daylight Time (UTC-8)",
  "AKST - Alaska Standard Time (UTC-9)",
  "AMST - Amazon Summer Time (UTC-3)",
  "AMT - Amazon Time (UTC-4)",
  "ART - Argentina Time (UTC-3)",
  "AST - Atlantic Standard Time (UTC-4)",
  "AWST - Australian Western Standard Time (UTC+8)",
  "AZOST - Azores Standard Time (UTC+0)",
  "AZT - Azerbaijan Time (UTC+4)",
  "BDT - Brunei Darussalam Time (UTC+8)",
  "BRT - Brasília Time (UTC-3)",
  "BST - British Summer Time (UTC+1)",
  "BTT - Bhutan Time (UTC+6)",
  "CAT - Central Africa Time (UTC+2)",
  "CCT - Cocos Islands Time (UTC+6:30)",
  "CDT - Central Daylight Time (UTC-5)",
  "CEST - Central European Summer Time (UTC+2)",
  "CET - Central European Time (UTC+1)",
  "CHADT - Chatham Daylight Time (UTC+13:45)",
  "CHAST - Chatham Standard Time (UTC+12:45)",
  "CHOT - Choibalsan Time (UTC+8)",
  "CHOST - Choibalsan Summer Time (UTC+9)",
  "CHST - Chamorro Standard Time (UTC+10)",
  "CHUT - Chuuk Time (UTC+10)",
  "CIT - Central Indonesia Time (UTC+8)",
  "CKT - Cook Island Time (UTC-10)",
  "CLST - Chile Summer Time (UTC-3)",
  "CLT - Chile Standard Time (UTC-4)",
  "COT - Colombia Time (UTC-5)",
  "CST - Central Standard Time (UTC-6)",
  "CT - China Time (UTC+8)",
  "CVT - Cape Verde Time (UTC-1)",
  "CWST - Central Western Standard Time (UTC+8:45)",
  "CXT - Christmas Island Time (UTC+7)",
  "DAVT - Davis Time (UTC+7)",
  "DDUT - Dumont d'Urville Time (UTC+10)",
  "EASST - Easter Island Summer Time (UTC-5)",
  "EAST - Easter Island Standard Time (UTC-6)",
  "EAT - East Africa Time (UTC+3)",
  "ECT - Ecuador Time (UTC-5)",
  "EDT - Eastern Daylight Time (UTC-4)",
  "EEST - Eastern European Summer Time (UTC+3)",
  "EET - Eastern European Time (UTC+2)",
  "EGST - Eastern Greenland Summer Time (UTC+0)",
  "EGT - Eastern Greenland Time (UTC-1)",
  "EIT - Eastern Indonesian Time (UTC+9)",
  "EST - Eastern Standard Time (UTC-5)",
  "FET - Further-Eastern European Time (UTC+3)",
  "FJT - Fiji Time (UTC+12)",
  "FKST - Falkland Islands Summer Time (UTC-3)",
  "FKT - Falkland Islands Time (UTC-4)",
  "FNT - Fernando de Noronha Time (UTC-2)",
  "GALT - Galapagos Time (UTC-6)",
  "GAMT - Gambier Islands Time (UTC-9)",
  "GET - Georgia Standard Time (UTC+4)",
  "GFT - French Guiana Time (UTC-3)",
  "GILT - Gilbert Island Time (UTC+12)",
  "GMT - Greenwich Mean Time (UTC+0)",
  "GST - Gulf Standard Time (UTC+4)",
  "GYT - Guyana Time (UTC-4)",
  "HAA - Heure Avancée de l'Atlantique (UTC-3)",
  "HAC - Heure Avancée du Centre (UTC-5)",
  "HADT - Hawaii-Aleutian Daylight Time (UTC-9)",
  "HAE - Heure Avancée de l'Est (UTC-4)",
  "HAP - Heure Avancée du Pacifique (UTC-7)",
  "HAR - Heure Avancée des Rocheuses (UTC-6)",
  "HAST - Hawaii-Aleutian Standard Time (UTC-10)",
  "HAT - Heure Avancée de Terre-Neuve (UTC-2:30)",
  "HAY - Heure Avancée du Yukon (UTC-8)",
  "HKT - Hong Kong Time (UTC+8)",
  "HOVST - Hovd Summer Time (UTC+8)",
  "HOVT - Hovd Time (UTC+7)",
  "HST - Hawaii Standard Time (UTC-10)",
  "ICT - Indochina Time (UTC+7)",
  "IDT - Israel Daylight Time (UTC+3)",
  "IOT - Indian Chagos Time (UTC+6)",
  "IRDT - Iran Daylight Time (UTC+4:30)",
  "IRKST - Irkutsk Summer Time (UTC+9)",
  "IRKT - Irkutsk Time (UTC+8)",
  "IRST - Iran Standard Time (UTC+3:30)",
  "IST - Indian Standard Time (UTC+5:30)",
  "JST - Japan Standard Time (UTC+9)",
  "KALT - Kaliningrad Time (UTC+2)",
  "KGT - Kyrgyzstan Time (UTC+6)",
  "KOST - Kosrae Time (UTC+11)",
  "KRAT - Krasnoyarsk Time (UTC+7)",
  "KST - Korea Standard Time (UTC+9)",
  "KUYT - Kuybyshev Time (UTC+4)",
  "LEST - Lord Howe Summer Time (UTC+11)",
  "LINT - Line Islands Time (UTC+14)",
  "MAGT - Magadan Time (UTC+12)",
  "MART - Marquesas Time (UTC-9:30)",
  "MAWT - Mawson Time (UTC+5)",
  "MDT - Mountain Daylight Time (UTC-6)",
  "MET - Middle European Time (UTC+1)",
  "MEST - Middle European Summer Time (UTC+2)",
  "MHT - Marshall Islands Time (UTC+12)",
  "MIST - Macquarie Island Station Time (UTC+11)",
  "MIT - Marquesas Islands Time (UTC-9:30)",
  "MMST - Myanmar Standard Time (UTC+6:30)",
  "MMT - Myanmar Time (UTC+6:30)",
  "MSK - Moscow Standard Time (UTC+3)",
  "MST - Mountain Standard Time (UTC-7)",
  "MUT - Mauritius Time (UTC+4)",
  "MVT - Maldives Time (UTC+5)",
  "MYT - Malaysia Time (UTC+8)",
  "NCT - New Caledonia Time (UTC+11)",
  "NDT - Newfoundland Daylight Time (UTC-2:30)",
  "NFT - Norfolk Time (UTC+11:30)",
  "NPT - Nepal Time (UTC+5:45)",
  "NST - Newfoundland Standard Time (UTC-3:30)",
  "NUT - Niue Time (UTC-11)",
  "NZDT - New Zealand Daylight Time (UTC+13)",
  "NZST - New Zealand Standard Time (UTC+12)",
  "OMSST - Omsk Summer Time (UTC+7)",
  "OMST - Omsk Standard Time (UTC+7)",
  "ORAT - Oral Time (UTC+5)",
  "PDT - Pacific Daylight Time (UTC-7)",
  "PET - Peru Time (UTC-5)",
  "PETST - Kamchatka Summer Time (UTC+12)",
  "PETT - Kamchatka Time (UTC+12)",
  "PGT - Papua New Guinea Time (UTC+10)",
  "PHOT - Phoenix Island Time (UTC+13)",
  "PHT - Philippine Time (UTC+8)",
  "PKT - Pakistan Standard Time (UTC+5)",
  "PMDT - Pierre & Miquelon Daylight Time (UTC-2)",
  "PMST - Pierre & Miquelon Standard Time (UTC-3)",
  "PONT - Pohnpei Standard Time (UTC+11)",
  "PST - Pacific Standard Time (UTC-8)",
  "PYT - Paraguay Time (UTC-4)",
  "PYT - Pyongyan Time (UTC+8:30)",
  "QYZT - Qyzylorda Time (UTC+6)",
  "RET - Réunion Time (UTC+4)",
  "ROTT - Rothera Research Station Time (UTC-3)",
  "SAKT - Sakhalin Time (UTC+11)",
  "SAMT - Samara Time (UTC+4)",
  "SAST - South Africa Standard Time (UTC+2)",
  "SBT - Solomon Islands Time (UTC+11)",
  "SCT - Seychelles Time (UTC+4)",
  "SDT - Samoa Daylight Time (UTC+14)",
  "SGT - Singapore Time (UTC+8)",
  "SRET - Srednekolymsk Time (UTC+11)",
  "SRT - Suriname Time (UTC-3)",
  "SRT - Sri Lanka Time (UTC+5:30)",
  "SST - Samoa Standard Time (UTC+13)",
  "SYOT - Showa Station Time (UTC+3)",
  "TAHT - Tahiti Time (UTC-10)",
  "TFT - French Southern and Antarctic Time (UTC+5)",
  "TJT - Tajikistan Time (UTC+5)",
  "TKT - Tokelau Time (UTC+13)",
  "TLT - Timor-Leste Time (UTC+9)",
  "TMT - Turkmenistan Time (UTC+5)",
  "TRT - Turkey Time (UTC+3)",
  "TOT - Tonga Time (UTC+13)",
  "TVT - Tuvalu Time (UTC+12)",
  "ULAST - Ulaanbaatar Summer Time (UTC+9)",
  "ULAT - Ulaanbaatar Time (UTC+8)",
  "UTC - Coordinated Universal Time (UTC+0)",
  "UYST - Uruguay Summer Time (UTC-2)",
  "UYT - Uruguay Time (UTC-3)",
  "UZT - Uzbekistan Time (UTC+5)",
  "VET - Venezuela Time (UTC-4)",
  "VLAST - Vladivostok Summer Time (UTC+11)",
  "VLAT - Vladivostok Time (UTC+10)",
  "VOST - Vostok Station Time (UTC+6)",
  "VUT - Vanuatu Time (UTC+11)",
  "WAKT - Wake Island Time (UTC+12)",
  "WAST - West Africa Summer Time (UTC+2)",
  "WAT - West Africa Time (UTC+1)",
  "WEST - Western European Summer Time (UTC+1)",
  "WET - Western European Time (UTC+0)",
  "WFT - Wallis and Futuna Time (UTC+12)",
  "WGST - Western Greenland Summer Time (UTC-2)",
  "WGT - Western Greenland Time (UTC-3)",
  "WIB - Western Indonesian Time (UTC+7)",
  "WIT - Eastern Indonesian Time (UTC+9)",
  "WITA - Central Indonesian Time (UTC+8)",
  "WST - West Samoa Time (UTC+14)",
  "WST - Western Sahara Summer Time (UTC+1)",
  "YAKT - Yakutsk Time (UTC+9)",
  "YEKT - Yekaterinburg Time (UTC+5)",
];

