#!/bin/sh

dir="$HOME/Videos/Movies"

if [ -z "$dir" ]; then
  echo "Directory is missing"
  exit 1
fi

cd "$dir" || exit
# Loop through each directory and zip its contents

upload_zip() {
  local file="$1"
  echo "Uploading $file to Nitroflare"
  curl \
    -F "user=d4394a381ca70336aa72dfffba5360589644b1f3" \
    -F "files=@$file" \
    $(curl http://nitroflare.com/plugins/fileupload/getServer)
}

for f in *.zip; do
  upload_zip "$f"
done
