name = "Bob"
data = [
    "Fullstack",
    "Fullstack",
    "AI",
    "Fullstack",
    "Fullstack",
    "Fullstack",
    "Fullstack",
    "Fullstack",
    "AI",
    "PM",
    "Fullstack",
    "Flutter",
    "Data Analyst",
    "Blockchain",
    "NSP",
    "NSP",
    "NSP",
    "Blockchain",
    "Fullstack",
    "AI",
    "Blockchain",
    "Data Analyst",
    "UI/UX",
    "PMO",
    "CEO",
    "CEO - Ghana",
    "Business Development",
    "HR",
    "CTO",
    "NSP",
    "Devops, AI",
    "Devops",
    "Devop, Mobile developer",
    "Administrator",
    "QA",
    "QA",
]

unique_items = list(set(data))

print(unique_items)
