#!/bin/bash

contents='{\n  "kind": "identitytoolkit#VerifyPasswordResponse",\n  "localId": "some-awesome-token",\n  "email": "meitar@aurec.co",\n  "displayName": "",\n  "idToken": "some-awesome-token",\n  "registered": true,\n  "refreshToken": "some-awesome-token",\n  "expiresIn": "3600"\n}\n'


echo -e $contents | jq '.idToken' | sed 's/"//g'
